import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

/**
 * ? Absolute overides the template if there is any
 * ? Default is the default title if the page doesn't have any
 * ? Template used when adding suffix or prefix in the title
 */
export const metadata: Metadata = {
  title: {
    default: "Nextjs 14 Tutorials - Codevolution",
    template: "%s | Codevolution",
  },
  // title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className='text-center w-full px-4 py-4 bg-cyan-900'>Header</header>
        {children}
        <footer className='text-center w-full px-4 py-4 bg-rose-600'>Footer</footer>
      </body>
    </html>
  )
}
